#!/usr/bin/env bash

export OPTIONS="-A:dev -J-XX:-OmitStackTraceInFastThrow -J-Xms50m -J-Xmx512m -J-Djdk.attach.allowAttachSelf -J-XX:+UnlockDiagnosticVMOptions -J-XX:+DebugNonSafepoints";

set -ex
exec clojure $OPTIONS -M -m rebel-readline.main
